### ISSUE TITLE
Feedback style

### ISSUE THREAD

**Issue by roberrrt-s** [lennartdeknikker/frontend-data#10]
Hi Lennart, ik kan gaan zeuren dat je je settings beter in een settings.json kan stoppen en die dan weer kan importeren met `import *  from /settings.json/` en die dan als `const settings = JSON.parse(settings) `kan verwerken, maar dat zou echt mierenneukerij zijn. 

Dus ik doe het toch, verder heb ik niets aan te merken, behalve dat ik erg vrolijk wordt als ik naar je code kijk. Veel succes nog deze week.

**Comment by lennartdeknikker** [comment]
Awesome!, bedankt voor het nakijken. Heb het aangepast!
